### ISSUE TITLE
Web UI does not work

### ISSUE THREAD

**Issue by averemee-si** [aws-samples/nft-marketplace#5]
Hello,

After implementing all instructions from README.md/Blockchain workshop article Web UI does not works. After opening page at 8080 web page links and then shows empty screen. JavaScript console contains:
```
...
...
UserView.tsx:56 Uncaught TypeError: this.props.registeredAssets.filter is not a function
    at UserView.getAccountAssets (UserView.tsx:56:1)
    at renderAssetRegistration (UserView.tsx:98:1)
    at UserView.render (UserView.tsx:154:1)
    at finishClassComponent (react-dom.development.js:17485:1)
    at updateClassComponent (react-dom.development.js:17435:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365:1)
    at GlobalContext.tsx:104:1
...
...
```
Please help in resolving this issue

Regards,
Aleksei

**Comment by waganse** [comment]
@averemee-si 
Please check your region in `ShareToWinRestApi/dblogic.js`. 

```
    constructor(){
        //AWS.config.update({region:'us-east-1'})
        this.dbClient=new AWS.DynamoDB.DocumentClient({apiVersion:'2012-08-10',region: 'us-east-1'}); <--- Check your region!
        this.dbTable='ShareToWin';

        this.createItemInDb=this.createItemInDb.bind(this);
        this.getItemFromDb=this.getItemFromDb.bind(this);
        this.getAllItems=this.getAllItems.bind(this);
    }
```
